services:
  - type: web
    name: practice-weather-app-backend
    runtime: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: KMA_KEY
        sync: false
